language: java
jdk: oraclejdk11

before_install:
  - chmod +x mvnw
services:
  - docker
addons:
  sonarcloud:
    organization: "sandipan-sonar"
    token: $SONAR_TOKEN
  coverity_scan:
    project:
      name: sandipan-git/product-service
      version: 1.0
      description: product-service
    notification_email: work.sandipan@gmail.com
    build_command_prepend: ./configure
    build_command: make
    branch_pattern: master
script:
  - ./mvnw clean compile jib:build sonar:sonar -Pcoverage verify
deploy:
  provider: script
  script: bash deploy.sh
  on:
branch: master

