spring:
  application:
  name: product-service
  profiles:
    active:
    - dev


---
spring:
  profiles: dev
server:
  port: 8000
auth0:
  issuer: https://dhobighat-dev.us.auth0.com/
  apiAudience: https://product.service/api
---

spring:
  profiles: production
server:
  port: 8000


